### PR TITLE
wow

### PR DESCRIPTION
**Pull request by Awpteamoose**
I am grateful for gnome.

### CODE REVIEW

**Comment by Awpteamoose** [comment]
idk why is it failing, doesn't seem to be my code

**Comment by ndelangen** [comment]
I might have to create a second github app with permissions to set status checks..

Definitely not your code's fault, indeed.

**Comment by ndelangen** [comment]
@Awpteamoose the reason is, you're running from a fork.

I can't solve this with an extra github app, because your repo doesn't have the github app installed, and also doesn't have the required secrets & vars.

You need to create a branch on this remote, and re-create the PR local to this repo.
Screenshot 2024-03-14 at 09 10 51

Alternatively, if you think the process of creating from forks should be supported, I can investigate maybe reporting the status checks from an action defined on `main`-branch.. similar to these:
Screenshot 2024-03-14 at 09 12 56

... but then run the code from the fork... But that seems more complex, and would run the code twice.

But I imagined that the concept of PR from forks might be a bit to foreign from some people new to github anyway, so though it would provide some security, it would be add the requirement to explain git on a deeper level with multiple remotes and syncing that, to new users.

**Comment by ndelangen** [comment]
Your fork doesn't allow me to force push (to remove my commits), so I'll just revert them.

**Pull request closed without merging**
